name: CI Workflow

on:
    pull_request: 
        branches: [ main ]

jobs:
    test_pull_requests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: 22
            - run: npm ci
            - run: npm test
            - run: npm run build
